# 基础格式文件
# 更多参见: http://jekyllrb.com/docs/permalinks/
permalink: /:title                                 # 文章的永久链接格式

markdown: redcarpet                                # 代码风格
highlighter: pygments                              # 代码风格
paginate: 20                                       # 每一个页帖子的显示数量
paginate_path: "page/:num"                         # 显示格式

#这里是网站主页配置，管理一些基本信息
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://inkiyinji.github.io

description : 好好学习，天天向上
title: 因吉                                        # 网站标题
logo: /assets/images/avatar_homepage.gif           # 主页图标
keywords: 因吉, 学习                               # 网页关键词，用','分隔
cover: /assets/images/cover_background.jpg         # 背景图像
language:                                          # 语言设置，常用的有zh-Hans、zh-CN
timezone: Asia/Shanghai                            # 时区

author: Inki
  name: Inki
  maxim: Guluuu
  role: Jekyll Theme
  email: inki.yinji@qq.com
  github: InkiYinji
  csdn: weixin_44575152
  twitter: YinjiInki
  facebook: goileolee
  googleplus: +goileolee
  bio: "你好，我是因吉"
  uno-dbyll: /assets/images/avatar_homepage.gif
